### ISSUE TITLE
Distortion from projectRaster

### ISSUE THREAD

**Issue by Senkichi** [PLJV/BrotherOrange#2]
```
if((!compareCRS(projection(landfire_stack), projection(world_stack)))|(!landfire_stack@extent==world_stack@extent)){
      landfire_stack <- projectRaster(landfire_stack, world_stack)
    }
    if((!compareCRS(projection(bio_raster), projection(world_stack)))|(!bio_raster@extent==world_stack@extent)){
      bio_raster <- projectRaster(bio_raster, world_stack)
    }
  } else {
    if((!compareCRS(projection(landfire_stack), projection(world_stack)))|(!landfire_stack@extent==world_stack@extent)){
      landfire_stack <- projectRaster(landfire_stack, world_stack)
    }
    if((!compareCRS(projection(bio_raster), projection(world_stack)))|(!bio_raster@extent==world_stack@extent)){
      bio_raster <- projectRaster(bio_raster, world_stack)
    }
  }

```
The above section of code from crop_and_combine is meant to fix the annoying problem we had with the extents of the different rasters barely not aligning, and therefore being unstackable. But when projectRaster for example projects the bio_raster (ebird raster), the range goes from 0,1 (what we want and have after successful rasterization of the checklists) to -0.497389, 1.479666. This leads me to believe that the cells are being distorted and altered. A similar phenomenon happens to the landfire data.

The first solution that occurred to me was change which raster is used as the standard by which other rasters should be projected to. Eg rather than projecto to match worldclim, we project worldclim and landfire to match ebird. But since 2/3 of our stack are categorical, there would always be some potentially debilitating distortion of some of the categorical variables.

**Comment by Senkichi** [comment]
that code starts at line 565

**Comment by ktaylora** [comment]
I'll take a look. And oy! Wrap your code pastes using the <> button.

**Comment by ktaylora** [comment]
Starting at [line 565](https://github.com/PLJV/BrotherOrange/blob/84310f2f2e102bdc62c9bfefded3d34a869cdf00/R/functions.R#L565):
We are using raster::projectRaster here to transform the CRS. Because the grid extents are off, this will not result in a stackable object. I think we have to interpolate for the "missing" values across a target grid to make the grids stackable. I'd try this: 

1.) change your projectRaster calls so they explicitly deal with making a consistent CRS:
`landfire_stack <- projectRaster(landfire_stack, world_stack)`
to 
`landfire_stack <- raster::projectRaster(from=landfire_stack, crs=sp::CRS(raster::projection(world_stack))`

2.) and then add a line that does the interpolation for our misaligned grid cells. This should go fairly quick now that the CRS's are in agreement:
`landfire_stack <- raster::resample(landfire_stack, world_stack, method='ngb')`

Give that a whirl and let me know if the extents are still misaligned. You might think on the method interpolator, too. I think nearest neighbors is more appropriate to use for this aggregation, because the landfire data are ordinal and bilinear interpolation would produce values that are not actually observed as landfire percent-cover or veg-height classes.

**Comment by Senkichi** [comment]
The extents are aligned, but the range is still busted. Now for the bio_raster its -0.4342056, 1.318095 rather than the desired 0,1. I'd like to say that we can class the negative values as 0 and the positive values as 1, but I don't think that's quite correct.

**Comment by ktaylora** [comment]
Weird. We shouldn't have done anything to the world_stack? We only reprojected/resampled the landfire stack.

**Comment by Senkichi** [comment]
Yeah, I'm using world_stack as the template as of now

**Comment by Senkichi** [comment]
And yeah, range is just the raster min/max values

**Comment by Senkichi** [comment]
@ktaylora it now stacks with stack = T. hopefully it doesn't fuck with the analysis too much

**Comment by ktaylora** [comment]
refactoring -- fixed.
